spring:
  application:
    name: Planilha de gastos

  datasource:
    url: jdbc:h2:file:~/AppData/Local/Controle Gastos/db
    driverClassName: org.h2.Driver
    username: user
    password: sa

    h2:
      console:
        enabled: true

    jpa:
      database: h2
      generate-ddl: true
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true

      hibernate:
        ddl-auto: update

server:
  error:
    include-stacktrace: never
